name: expense_tracker_pro_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: ^3.10.8

dependencies:
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  intl: ^0.19.0
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "/Users/ganbayr/expence_tracker_pro/expense_tracker_pro_new/ea04e3a1-dc74-4ee2-a65d-9b0285e823e9.png"
  min_sdk_android: 21
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "/Users/ganbayr/expence_tracker_pro/expense_tracker_pro_new/ea04e3a1-dc74-4ee2-a65d-9b0285e823e9.png"
  web:
    generate: false