// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1flznMnYBSw8jmryCzmdyrwPNW6t6xX4',
    appId: '1:8768613907:web:8963de6d9bb6d2645359e6',
    messagingSenderId: '8768613907',
    projectId: 'expense-tracker-pro-new',
    authDomain: 'expense-tracker-pro-new.firebaseapp.com',
    storageBucket: 'expense-tracker-pro-new.firebasestorage.app',
    measurementId: 'G-3S8S9278M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDrCPf64_2pbHjJpFrl7QkzA8wKJ_hB4',
    appId: '1:8768613907:android:a2a3878a103dc4945359e6',
    messagingSenderId: '8768613907',
    projectId: 'expense-tracker-pro-new',
    storageBucket: 'expense-tracker-pro-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZE5HzBAnWhxq-VUVD6PQcFUkPOPxNZMI',
    appId: '1:8768613907:ios:c3c1ba695147b47a5359e6',
    messagingSenderId: '8768613907',
    projectId: 'expense-tracker-pro-new',
    storageBucket: 'expense-tracker-pro-new.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerProNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZE5HzBAnWhxq-VUVD6PQcFUkPOPxNZMI',
    appId: '1:8768613907:ios:c3c1ba695147b47a5359e6',
    messagingSenderId: '8768613907',
    projectId: 'expense-tracker-pro-new',
    storageBucket: 'expense-tracker-pro-new.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerProNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1flznMnYBSw8jmryCzmdyrwPNW6t6xX4',
    appId: '1:8768613907:web:b661756316b8db735359e6',
    messagingSenderId: '8768613907',
    projectId: 'expense-tracker-pro-new',
    authDomain: 'expense-tracker-pro-new.firebaseapp.com',
    storageBucket: 'expense-tracker-pro-new.firebasestorage.app',
    measurementId: 'G-K26F2SB454',
  );
}
