// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXrZlz8ez5f1foUFaIortjZPSwYdR0gJ4',
    appId: '1:97152441330:web:cf8cce3baf1f41f5baa96b',
    messagingSenderId: '97152441330',
    projectId: 'neew-438f5',
    authDomain: 'neew-438f5.firebaseapp.com',
    storageBucket: 'neew-438f5.firebasestorage.app',
    measurementId: 'G-M2NLHQRWRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIiESW_HaYsgrokkfJT8VDn_jnpiRFqk',
    appId: '1:97152441330:android:4c53cfca93208c19baa96b',
    messagingSenderId: '97152441330',
    projectId: 'neew-438f5',
    storageBucket: 'neew-438f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaPps8tiwyNPKdUYJ8FLWVKNXJ-UbkxEA',
    appId: '1:97152441330:ios:4b60099749d7c588baa96b',
    messagingSenderId: '97152441330',
    projectId: 'neew-438f5',
    storageBucket: 'neew-438f5.firebasestorage.app',
    iosClientId: '97152441330-p2bo74velra8edks21aimdsi0mv2dbd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerProNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaPps8tiwyNPKdUYJ8FLWVKNXJ-UbkxEA',
    appId: '1:97152441330:ios:4b60099749d7c588baa96b',
    messagingSenderId: '97152441330',
    projectId: 'neew-438f5',
    storageBucket: 'neew-438f5.firebasestorage.app',
    iosClientId: '97152441330-p2bo74velra8edks21aimdsi0mv2dbd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerProNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXrZlz8ez5f1foUFaIortjZPSwYdR0gJ4',
    appId: '1:97152441330:web:8e65af08a288a5f0baa96b',
    messagingSenderId: '97152441330',
    projectId: 'neew-438f5',
    authDomain: 'neew-438f5.firebaseapp.com',
    storageBucket: 'neew-438f5.firebasestorage.app',
    measurementId: 'G-WZ3M4FH29S',
  );

}