class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'on': 'On',
      'off': 'Off',
      'currency': 'Currency',
      'select_currency': 'Select Currency',
      'security': 'Security',
      'change_password': 'Change Password',
      'update_password': 'Update your password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'cancel': 'Cancel',
      'save': 'Save',
      'data': 'Data',
      'clear_all_data': 'Clear All Data',
      'clear_data_sub': 'Delete all transactions & categories',
      'clear_confirm_title': 'Clear All Data',
      'clear_confirm_body': 'Delete all transactions & categories?\nThis action cannot be undone!',
      'clear': 'Clear',
      'about': 'About',
      'version': 'Version',
      'app_name': 'App Name',
      'passwords_no_match': 'Passwords do not match!',
      'password_changed': '✅ Password changed!',
      'data_cleared': '✅ All data cleared!',
      'error': 'Error',
      'language': 'Language',
      'select_language': 'Select Language',
      'dashboard': 'Dashboard',
      'analytics': 'Analytics',
      'expense_breakdown': 'Expense Breakdown',
      'income_breakdown': 'Income Breakdown',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'swipe_income': 'Swipe for Income →',
      'no_expense': 'No expense data yet',
      'no_income': 'No income data yet',
      'total': 'Total',
      'expenses': 'Expenses',
      'transactions': 'Transactions',
      'search_transactions': 'Search transactions...',
      'all': 'All',
      'balance': 'Balance',
      'no_transactions': 'No transactions yet',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'no_account': "Don't have an account? Register",
      'categories': 'Categories',
      'profile': 'Profile',
      'verified': 'Verified',
      'verify_email': 'Verify email',
      'personal_info': 'Personal Info',
      'display_name': 'Display Name',
      'save_changes': 'Save Changes',
      'settings_sub': 'Currency, Dark mode, Data',
      'logout': 'Logout',
      'delete_account': 'Delete Account',
      'delete_confirm': 'Are you sure? This action cannot be undone.',
      'delete': 'Delete',
      'photo_updated': '✅ Photo updated!',
      'profile_updated': '✅ Profile updated!',
      'verify_sent': 'Verification email sent!',
      'monthly_report': 'Monthly Report',
      'net_expense': 'Net Balance',
      'daily_overview': 'Daily Overview',
      'no_data': 'No data',
      'expense_by_category': 'Expense by Category',
      'add_transaction': 'Add Transaction',
      'edit_transaction': 'Edit Transaction',
      'amount': 'Amount',
      'category': 'Category',
      'select_category': 'Select Category',
      'subcategory': 'Subcategory',
      'select_subcategory': 'Select Subcategory',
      'note_optional': 'Note (optional)',
      'add_category': 'Add Category',
      'update': 'Update',
      'enter_amount': 'Enter amount',
      'invalid_amount': 'Invalid amount',
      'select_category_error': 'Select category',
      'edit_category': 'Edit Category',
      'category_name_en': 'Category name (English)',
      'category_name_mn': 'Category name (Mongolian)',
      'select_emoji': 'Select Emoji',
      'delete_category': 'Delete Category',
      'are_you_sure': 'Are you sure?',
      'budget': 'Budget',
      'set_budget': 'Set Budget',
      'monthly_budget': 'Monthly Budget',
      'budget_limit': 'Budget Limit',
      'no_budget': 'No budget set',
      'over_budget': 'Over budget!',
      'budget_used': 'used',
      'delete_budget': 'Remove Budget',
    },
    'mn': {
      'settings': 'Тохиргоо',
      'appearance': 'Харагдац',
      'dark_mode': 'Харанхуй горим',
      'on': 'Асаалттай',
      'off': 'Унтраалттай',
      'currency': 'Валют',
      'select_currency': 'Валют сонгох',
      'security': 'Аюулгүй байдал',
      'change_password': 'Нууц үг солих',
      'update_password': 'Нууц үгээ шинэчлэх',
      'current_password': 'Одоогийн нууц үг',
      'new_password': 'Шинэ нууц үг',
      'confirm_password': 'Нууц үг баталгаажуулах',
      'cancel': 'Цуцлах',
      'save': 'Хадгалах',
      'data': 'Өгөгдөл',
      'clear_all_data': 'Бүгдийг устгах',
      'clear_data_sub': 'Бүх гүйлгээ, ангилал устгах',
      'clear_confirm_title': 'Бүгдийг устгах уу?',
      'clear_confirm_body': 'Бүх гүйлгээ, ангилал устгах уу?\nЭнэ үйлдлийг буцаах боломжгүй!',
      'clear': 'Устгах',
      'about': 'Тухай',
      'version': 'Хувилбар',
      'app_name': 'Апп нэр',
      'passwords_no_match': 'Нууц үг таарахгүй байна!',
      'password_changed': '✅ Нууц үг солигдлоо!',
      'data_cleared': '✅ Бүх өгөгдөл устгагдлаа!',
      'error': 'Алдаа',
      'language': 'Хэл',
      'select_language': 'Хэл сонгох',
      'dashboard': 'Хяналтын самбар',
      'analytics': 'Шинжилгээ',
      'expense_breakdown': 'Зарлагын задаргаа',
      'income_breakdown': 'Орлогын задаргаа',
      'total_balance': 'Нийт үлдэгдэл',
      'income': 'Орлого',
      'expense': 'Зарлага',
      'swipe_income': 'Орлого харах →',
      'no_expense': 'Зарлага байхгүй',
      'no_income': 'Орлого байхгүй',
      'total': 'Нийт',
      'expenses': 'Зарлага',
      'transactions': 'Гүйлгээнүүд',
      'search_transactions': 'Гүйлгээ хайх...',
      'all': 'Бүгд',
      'balance': 'Үлдэгдэл',
      'no_transactions': 'Гүйлгээ байхгүй байна',
      'email': 'Имэйл',
      'password': 'Нууц үг',
      'forgot_password': 'Нууц үг мартсан уу?',
      'login': 'Нэвтрэх',
      'no_account': 'Бүртгэл байхгүй юу? Бүртгүүлэх',
      'categories': 'Ангилалууд',
      'profile': 'Профайл',
      'verified': 'Баталгаажсан',
      'verify_email': 'Имэйл баталгаажуулах',
      'personal_info': 'Хувийн мэдээлэл',
      'display_name': 'Нэр',
      'save_changes': 'Хадгалах',
      'settings_sub': 'Валют, Харанхуй горим, Өгөгдөл',
      'logout': 'Гарах',
      'delete_account': 'Бүртгэл устгах',
      'delete_confirm': 'Итгэлтэй байна уу? Энэ үйлдлийг буцаах боломжгүй.',
      'delete': 'Устгах',
      'photo_updated': '✅ Зураг шинэчлэгдлээ!',
      'profile_updated': '✅ Профайл шинэчлэгдлээ!',
      'verify_sent': 'Баталгаажуулах имэйл илгээгдлээ!',
      'monthly_report': 'Сарын тайлан',
      'net_balance': 'Цэвэр үлдэгдэл',
      'daily_overview': 'Өдрийн хэлбэлзэл',
      'no_data': 'Өгөгдөл байхгүй',
      'expense_by_category': 'Ангиллаар зарлага',
      'add_transaction': 'Гүйлгээ нэмэх',
      'edit_transaction': 'Гүйлгээ засах',
      'amount': 'Дүн',
      'category': 'Ангилал',
      'select_category': 'Ангилал сонгох',
      'subcategory': 'Дэд ангилал',
      'select_subcategory': 'Дэд ангилал сонгох',
      'note_optional': 'Тэмдэглэл (заавал биш)',
      'add_category': 'Ангилал нэмэх',
      'update': 'Шинэчлэх',
      'enter_amount': 'Дүн оруулах',
      'invalid_amount': 'Буруу дүн',
      'select_category_error': 'Ангилал сонгоно уу',
      'edit_category': 'Ангилал засах',
      'category_name_en': 'Ангилалын нэр (Англи)',
      'category_name_mn': 'Ангилалын нэр (Монгол)',
      'select_emoji': 'Emoji сонгох',
      'delete_category': 'Ангилал устгах',
      'are_you_sure': 'Итгэлтэй байна уу?',
      'budget': 'Төсөв',
      'set_budget': 'Төсөв тохируулах',
      'monthly_budget': 'Сарын төсөв',
      'budget_limit': 'Төсвийн хязгаар',
      'no_budget': 'Төсөв тохируулаагүй',
      'over_budget': 'Төсөв хэтэрлээ!',
      'budget_used': 'зарцуулсан',
      'delete_budget': 'Төсөв устгах',
    },
  };

  static String get(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['en']?[key] ?? key;
  }
}