class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'on': 'On',
      'off': 'Off',
      'currency': 'Currency',
      'select_currency': 'Select Currency',
      'security': 'Security',
      'change_password': 'Change Password',
      'update_password': 'Update your password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'cancel': 'Cancel',
      'save': 'Save',
      'data': 'Data',
      'clear_all_data': 'Clear All Data',
      'clear_data_sub': 'Delete all transactions & categories',
      'clear_confirm_title': 'Clear All Data',
      'clear_confirm_body': 'Delete all transactions & categories?\nThis action cannot be undone!',
      'clear': 'Clear',
      'about': 'About',
      'version': 'Version',
      'app_name': 'App Name',
      'passwords_no_match': 'Passwords do not match!',
      'password_changed': '✅ Password changed!',
      'data_cleared': '✅ All data cleared!',
      'error': 'Error',
      'language': 'Language',
      'select_language': 'Select Language',
      'dashboard': 'Dashboard',
      'analytics': 'Analytics',
      'expense_breakdown': 'Expense Breakdown',
      'income_breakdown': 'Income Breakdown',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'swipe_income': 'Swipe for Income →',
      'no_expense': 'No expense data yet',
      'no_income': 'No income data yet',
      'total': 'Total',
      'expenses': 'Expenses',
      'transactions': 'Transactions',
'search_transactions': 'Search transactions...',
'all': 'All',
'balance': 'Balance',
'no_transactions': 'No transactions yet',
'email': 'Email',
'password': 'Password',
'forgot_password': 'Forgot Password?',
'login': 'Login',
'no_account': "Don't have an account? Register",
    },
    'mn': {
      'settings': 'Тохиргоо',
      'appearance': 'Харагдац',
      'dark_mode': 'Харанхуй горим',
      'on': 'Асаалттай',
      'off': 'Унтраалттай',
      'currency': 'Валют',
      'select_currency': 'Валют сонгох',
      'security': 'Аюулгүй байдал',
      'change_password': 'Нууц үг солих',
      'update_password': 'Нууц үгээ шинэчлэх',
      'current_password': 'Одоогийн нууц үг',
      'new_password': 'Шинэ нууц үг',
      'confirm_password': 'Нууц үг баталгаажуулах',
      'cancel': 'Цуцлах',
      'save': 'Хадгалах',
      'data': 'Өгөгдөл',
      'clear_all_data': 'Бүгдийг устгах',
      'clear_data_sub': 'Бүх гүйлгээ, ангилал устгах',
      'clear_confirm_title': 'Бүгдийг устгах уу?',
      'clear_confirm_body': 'Бүх гүйлгээ, ангилал устгах уу?\nЭнэ үйлдлийг буцаах боломжгүй!',
      'clear': 'Устгах',
      'about': 'Тухай',
      'version': 'Хувилбар',
      'app_name': 'Апп нэр',
      'passwords_no_match': 'Нууц үг таарахгүй байна!',
      'password_changed': '✅ Нууц үг солигдлоо!',
      'data_cleared': '✅ Бүх өгөгдөл устгагдлаа!',
      'error': 'Алдаа',
      'language': 'Хэл',
      'select_language': 'Хэл сонгох',
      'dashboard': 'Хяналтын самбар',
      'analytics': 'Шинжилгээ',
      'expense_breakdown': 'Зарлагын задаргаа',
      'income_breakdown': 'Орлогын задаргаа',
      'total_balance': 'Нийт үлдэгдэл',
      'income': 'Орлого',
      'expense': 'Зарлага',
      'swipe_income': 'Орлого харах →',
      'no_expense': 'Зарлага байхгүй',
      'no_income': 'Орлого байхгүй',
      'total': 'Нийт',
      'expenses': 'Зарлага',
      'transactions': 'Гүйлгээнүүд',
'search_transactions': 'Гүйлгээ хайх...',
'all': 'Бүгд',
'balance': 'Үлдэгдэл',
'no_transactions': 'Гүйлгээ байхгүй байна',
'email': 'Имэйл',
'password': 'Нууц үг',
'forgot_password': 'Нууц үг мартсан уу?',
'login': 'Нэвтрэх',
'no_account': 'Бүртгэл байхгүй юу? Бүртгүүлэх',
    },
  };

  static String get(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['en']?[key] ?? key;
  }
}